baseURL = "https://quiz.mxe.no/"
languageCode = "nb"
defaultContentLanguage = "nb"

title = "QUIZ!"
copyright = "Estensen MXE © Siden 2024"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params]
  title = "QUIZ!"
  attribution = false
  description = "QUIZ! av Mats Estensen (Estensen MXE)"
  keywords = "quiz,musikkquiz,oslo,drammen,norge,mats estensen,hestedirektoratets rockequiz,vaterland"
  images = ['images/qm.png']

  [params.social]
    twitter = 'matsest'

[outputs]
  home = ['HTML']
  section = ['HTML']

[params.author]
  headline = "Mats lager musikkquiz.."
  image = "images/og-image.png"  # path relative to static directory

  links = [
    { email = { href="mailto:mats.est+quiz@gmail.com", text="Send meg en e-post" }},
    { facebook = { href="https://www.facebook.com/hestedirektoratetsrockequiz", text = "Hestedirektoratets Rockequiz @ Vaterland" } },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { bandcamp = "https://username.bandcamp.com" },
    # { bluesky = "https://bsky.app/profile/username" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    { lastfm = { href="https://last.fm/user/matsest", text = "Last.fm (personlig)" }},
    # { linkedin = "https://linkedin.com/in/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    { spotify = { href="https://open.spotify.com/user/matsest", text = "Spotify (personlig)" }},
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x = "https://x.com/username" },
    # { youtube = "https://youtube.com/username" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"

